version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Raise pull requests for version updates
    # against the `main` branch
    target-branch: "main"
    # Labels on pull requests for version updates
    labels:
      - "dependencies"
      - "security"
    # Specify version update preferences
    versioning-strategy: increase
    # Allow up to 10 open pull requests for dependencies
    open-pull-requests-limit: 10
    # Add reviewers
    reviewers:
      - "Blackpenguin46"
    # Ignore certain dependencies
    ignore:
      # Ignore updates for packages with known issues
      - dependency-name: "@supabase/auth-helpers-nextjs"
        versions: [">=0.11.0"]
      - dependency-name: "@supabase/auth-helpers-shared"
        versions: [">=0.8.0"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Raise pull requests for version updates
    # against the `main` branch
    target-branch: "main"
    # Labels on pull requests for version updates
    labels:
      - "dependencies"
      - "github_actions"
    # Add reviewers
    reviewers:
      - "Blackpenguin46" 